import { createActionGroup, emptyProps, props } from '@ngrx/store';
import { Notification } from '../../../shared/models/notification.model';

export const NotificationActions = createActionGroup({
  source: 'Notifications',
  events: {
    /** Load notifications for the given user from the API */
    'Load': props<{ userId: string }>(),
    'Load Success': props<{ notifications: Notification[] }>(),
    'Load Failure': props<{ error: string }>(),

    /** Mark a single notification as read */
    'Mark As Read': props<{ notificationId: string }>(),

    /** Mark every notification as read */
    'Mark All As Read': emptyProps(),

    /** Optimistically prepend a notification generated by the session */
    'Add Notification': props<{ notification: Notification }>(),

    /** Clear all notifications (e.g. on logout) */
    'Clear': emptyProps(),
  },
});
