import { Injectable } from '@angular/core';
import { ExportMetadata } from '../../shared/models/report.models';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

@Injectable({ providedIn: 'root' })
export class ExportService {
  // ── PDF Table Export (jsPDF-AutoTable) ────────────────────────────────────

  exportTableToPdf(
    columns: string[],
    rows: (string | number)[][],
    metadata: ExportMetadata,
    fileName?: string,
  ): void {
    const doc = new jsPDF();
    const header = this._buildPdfHeader(metadata);

    doc.setFontSize(10);
    doc.text(header, 14, 15);

    autoTable(doc, {
      head: [columns],
      body: rows.map((r) => r.map(String)),
      startY: 32,
      styles: { fontSize: 9 },
      headStyles: { fillColor: [59, 130, 246] },
    });

    doc.save(fileName ?? `${this._safeFileName(metadata.reportTitle)}.pdf`);
  }

  // ── PDF Chart Export (html2canvas + jsPDF) ────────────────────────────────

  async exportChartToPdf(
    chartElement: HTMLElement,
    metadata: ExportMetadata,
    fileName?: string,
  ): Promise<void> {
    const html2canvas = (await import('html2canvas')).default;
    const canvas = await html2canvas(chartElement, { scale: 2, useCORS: true });
    const imgData = canvas.toDataURL('image/png');

    const doc = new jsPDF({ orientation: 'landscape' });
    const header = this._buildPdfHeader(metadata);

    doc.setFontSize(10);
    doc.text(header, 14, 15);

    const pageWidth = doc.internal.pageSize.getWidth();
    const imgWidth = pageWidth - 28;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    doc.addImage(imgData, 'PNG', 14, 32, imgWidth, imgHeight);
    doc.save(fileName ?? `${this._safeFileName(metadata.reportTitle)}.pdf`);
  }

  // ── Excel Export (SheetJS) ────────────────────────────────────────────────

  async exportToExcel(
    columns: string[],
    rows: (string | number)[][],
    metadata: ExportMetadata,
    fileName?: string,
  ): Promise<void> {
    const XLSX = await import('xlsx');

    const headerRows = this._buildSheetHeader(metadata);
    const data = [...headerRows, columns, ...rows.map((r) => r.map(String))];

    const worksheet = XLSX.utils.aoa_to_sheet(data);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Report');
    XLSX.writeFile(workbook, fileName ?? `${this._safeFileName(metadata.reportTitle)}.xlsx`);
  }

  // ── CSV Export (SheetJS) ──────────────────────────────────────────────────

  async exportToCsv(
    columns: string[],
    rows: (string | number)[][],
    metadata: ExportMetadata,
    fileName?: string,
  ): Promise<void> {
    const XLSX = await import('xlsx');

    const headerRows = this._buildSheetHeader(metadata);
    const data = [...headerRows, columns, ...rows.map((r) => r.map(String))];

    const worksheet = XLSX.utils.aoa_to_sheet(data);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Report');
    XLSX.writeFile(workbook, fileName ?? `${this._safeFileName(metadata.reportTitle)}.csv`, { bookType: 'csv' });
  }

  // ── PNG Export (html2canvas) ──────────────────────────────────────────────

  async exportToPng(
    chartElement: HTMLElement,
    metadata: ExportMetadata,
    fileName?: string,
  ): Promise<void> {
    const html2canvas = (await import('html2canvas')).default;
    const canvas = await html2canvas(chartElement, { scale: 2, useCORS: true });

    canvas.toBlob((blob) => {
      if (!blob) return;
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = fileName ?? `${this._safeFileName(metadata.reportTitle)}.png`;
      link.click();
      URL.revokeObjectURL(url);
    }, 'image/png');
  }

  // ── Private helpers ───────────────────────────────────────────────────────

  private _buildPdfHeader(metadata: ExportMetadata): string {
    return [
      metadata.reportTitle,
      `Generated: ${metadata.generationDate}`,
      `Generated by: ${metadata.generatingUserName}`,
    ].join('   |   ');
  }

  private _buildSheetHeader(metadata: ExportMetadata): string[][] {
    return [
      [metadata.reportTitle],
      [`Generated: ${metadata.generationDate}   |   Generated by: ${metadata.generatingUserName}`],
      [],
    ];
  }

  private _safeFileName(title: string): string {
    return title.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  }
}
