import { Injectable, inject } from '@angular/core';
import { Store } from '@ngrx/store';
import { take } from 'rxjs/operators';
import { Project } from '../../shared/models/project.model';
import { CandidateMatchResult } from '../../shared/models/candidate-match.model';
import { selectCurrentUser } from '../store/session/session.selectors';

@Injectable({ providedIn: 'root' })
export class PdfExportService {
  private readonly store = inject(Store);

  /**
   * Export a candidate matching report as PDF.
   * Requires jsPDF and jspdf-autotable to be installed:
   *   npm install jspdf jspdf-autotable
   */
  async exportCandidateReport(
    project: Project,
    results: CandidateMatchResult[]
  ): Promise<void> {
    let currentUserName = 'Unknown';
    this.store.select(selectCurrentUser).pipe(take(1)).subscribe((u) => {
      if (u) currentUserName = u.name;
    });

    try {
      // Dynamic imports to avoid breaking the build if jsPDF is not installed
      const jsPDFModule = await import('jspdf');
      const autoTableModule = await import('jspdf-autotable');
      const jsPDF = jsPDFModule.default ?? (jsPDFModule as unknown as { default: unknown }).default;
      const autoTable = (autoTableModule as unknown as { default: (doc: unknown, options: unknown) => void }).default;

      const doc = new (jsPDF as new (orientation: string, unit: string, format: string) => {
        text: (text: string, x: number, y: number, options?: unknown) => void;
        setFontSize: (size: number) => void;
        setFont: (font: string, style: string) => void;
        internal: { pageSize: { width: number } };
        save: (filename: string) => void;
      })('portrait', 'mm', 'a4');

      const pageWidth = doc.internal.pageSize.width;
      let y = 15;

      // Title
      doc.setFontSize(16);
      doc.setFont('helvetica', 'bold');
      doc.text(`Candidate Matching Report — ${project.name}`, 14, y);
      y += 8;

      // Meta
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text(`Generated: ${new Date().toLocaleDateString()}`, 14, y);
      y += 5;
      doc.text(`Generated by: ${currentUserName}`, 14, y);
      y += 10;

      // Table
      const tableData = results.map((r, i) => [
        String(i + 1),
        r.userName,
        r.department,
        `${r.matchScore}%`,
        r.availability,
        `${r.matchedCount}/${r.totalRequired}`,
      ]);

      autoTable(doc, {
        startY: y,
        head: [['Rank', 'Candidate', 'Department', 'Match Score', 'Availability', 'Skills Met']],
        body: tableData,
        styles: { fontSize: 9 },
        headStyles: { fillColor: [25, 118, 210] },
      });

      const safeProjectName = project.name.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
      doc.save(`candidates-${safeProjectName}.pdf`);
    } catch {
      // jsPDF not installed — fallback to CSV download
      this.exportAsCsv(project, results);
    }
  }

  private exportAsCsv(project: Project, results: CandidateMatchResult[]): void {
    const header = 'Rank,Candidate,Department,Match Score,Availability,Skills Met\n';
    const rows = results
      .map(
        (r, i) =>
          `${i + 1},"${r.userName}","${r.department}",${r.matchScore}%,"${r.availability}",${r.matchedCount}/${r.totalRequired}`
      )
      .join('\n');
    const csv = header + rows;
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    const safeProjectName = project.name.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
    a.download = `candidates-${safeProjectName}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  }
}
